server:
  port: ${PORT:5000}

base-url: /api

rollbar_token: ${rollbar_tkn}

spring:
  application:
    name: taskManager

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
